"""Load the static axe-core rule catalogue and expose per-rule tool helpers.

``vendor/axe-rules.json`` is generated by ``scripts/generate_axe_rules.py`` from the
vendored axe-core. Loading it here (instead of querying a live browser) means the
server can register one MCP tool per axe rule at import time without launching
Chromium.
"""

from __future__ import annotations

import json
from dataclasses import dataclass
from functools import lru_cache

from accessibility_mcp import config
from accessibility_mcp.rules import remediation

_RULES_PATH = config.VENDOR_DIR / "axe-rules.json"


@dataclass(frozen=True)
class AxeRule:
    rule_id: str
    description: str
    help: str
    help_url: str
    tags: tuple[str, ...]
    enabled: bool

    @property
    def tool_name(self) -> str:
        """MCP tool name for this rule, e.g. 'color-contrast' -> 'axe_color_contrast'."""
        safe = self.rule_id.replace("-", "_").replace(".", "_")
        return f"axe_{safe}"

    @property
    def wcag_criteria(self) -> list[str]:
        return remediation.wcag_criteria_from_tags(list(self.tags))

    @property
    def is_wcag(self) -> bool:
        return any(t.startswith(("wcag2", "wcag21", "wcag22")) for t in self.tags)

    def to_dict(self) -> dict:
        return {
            "rule_id": self.rule_id,
            "tool_name": self.tool_name,
            "description": self.description,
            "help": self.help,
            "help_url": self.help_url,
            "tags": list(self.tags),
            "wcag_criteria": self.wcag_criteria,
            "is_wcag": self.is_wcag,
            "enabled": self.enabled,
        }


@lru_cache(maxsize=1)
def _load() -> tuple[str, tuple[AxeRule, ...]]:
    if not _RULES_PATH.exists():
        # No catalogue generated yet — degrade to empty rather than crash import.
        return "unknown", ()
    data = json.loads(_RULES_PATH.read_text(encoding="utf-8"))
    rules = tuple(
        AxeRule(
            rule_id=r["ruleId"],
            description=r.get("description", ""),
            help=r.get("help", ""),
            help_url=r.get("helpUrl", ""),
            tags=tuple(r.get("tags", [])),
            enabled=bool(r.get("enabled", True)),
        )
        for r in data.get("rules", [])
    )
    return data.get("axe_version", "unknown"), rules


def axe_version() -> str:
    return _load()[0]


def all_rules() -> list[AxeRule]:
    return list(_load()[1])


def wcag_rules() -> list[AxeRule]:
    """Only rules tagged with a WCAG conformance level."""
    return [r for r in all_rules() if r.is_wcag]


@lru_cache(maxsize=1)
def _by_id() -> dict[str, AxeRule]:
    return {r.rule_id: r for r in all_rules()}


def get_rule(rule_id: str) -> AxeRule | None:
    return _by_id().get(rule_id)
